# Generated by Django 5.2.15 on 2026-06-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parkingspot_alter_parkingevent_zone_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='description',
        ),
    ]
