# Generated by Django 5.2.15 on 2026-06-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_parkingspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionLog',
        ),
    ]
