# Generated by Django 5.2.15 on 2026-06-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_parkingevent_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingevent',
            name='webcam_image_path',
        ),
    ]
