# Generated by Django 5.2.15 on 2026-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_parkingevent_vehicle_x_vehicle_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingevent',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='parkingevent',
            name='zone_type',
        ),
        migrations.AlterField(
            model_name='parkingevent',
            name='status',
            field=models.CharField(choices=[('DETECTED', 'Detected'), ('SCANNED', 'Scanned'), ('WARNING_ISSUED', 'Warning Issued')], db_index=True, default='DETECTED', max_length=15),
        ),
    ]
