# Generated by Django 5.2.15 on 2026-06-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_ocr_image_path_vehicleinfo_ocr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='amr_vehicle_x',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='amr_vehicle_y',
        ),
    ]
