# Generated by Django 5.2.15 on 2026-06-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('NORMAL', 'Normal'), ('ILLEGAL', 'Illegal')], max_length=10)),
                ('zone_type', models.CharField(choices=[('NORMAL_ZONE', 'Normal Zone'), ('DISABLED_ZONE', 'Disabled Zone'), ('FIRE_ZONE', 'Fire Zone')], max_length=15)),
                ('vehicle_x', models.FloatField()),
                ('vehicle_y', models.FloatField()),
                ('observation_x', models.FloatField()),
                ('observation_y', models.FloatField()),
                ('webcam_image_path', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('SCANNED', 'Scanned'), ('WARNING_ISSUED', 'Warning Issued')], db_index=True, default='DETECTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_events',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('ocr_image_path', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to='app.parkingevent')),
            ],
            options={
                'db_table': 'vehicle_info',
            },
        ),
    ]
