# Generated by Django 5.2.15 on 2026-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disabled_vehicle',
            },
        ),
    ]
