# Generated by Django 5.2.15 on 2026-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disabledvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('NORMAL', '일반'), ('COMPACT', '경차 전용'), ('DISABLED', '장애인 전용'), ('FIRE', '소방차 전용'), ('EV', '전기차 전용')], max_length=10)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'parking_spot',
            },
        ),
        migrations.AlterField(
            model_name='parkingevent',
            name='zone_type',
            field=models.CharField(choices=[('NORMAL', '일반'), ('COMPACT', '경차 전용'), ('DISABLED', '장애인 전용'), ('FIRE', '소방차 전용'), ('EV', '전기차 전용')], max_length=10),
        ),
    ]
