# Generated by Django 5.2.15 on 2026-06-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_parkingspot_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
