# Generated by Django 5.2.15 on 2026-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_detectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='amr_vehicle_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='amr_vehicle_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingevent',
            name='status',
            field=models.CharField(choices=[('DETECTED', 'Detected'), ('SCANNED', 'Scanned'), ('VERIFIED', 'Verified'), ('WARNING_ISSUED', 'Warning Issued')], db_index=True, default='DETECTED', max_length=15),
        ),
    ]
