# Generated by Django 5.2.15 on 2026-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vehicleinfo_amr_vehicle_x_vehicleinfo_amr_vehicle_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingevent',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ILLEGAL', 'Illegal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingevent',
            name='zone_type',
            field=models.CharField(blank=True, choices=[('Not', '주차구역 아님'), ('NORMAL', '정상 주차구역 (주황색)'), ('COMPACT', '경차 전용'), ('DISABLED', '장애인 전용'), ('FIRE', '소방차 전용'), ('EV', '전기차 전용')], max_length=10, null=True),
        ),
    ]
