# Generated by Django 5.2.15 on 2026-06-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_parkingevent_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='ocr_image_path',
            new_name='ocr_image',
        ),
    ]
