# Generated by Django 5.2.15 on 2026-06-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_vehicleinfo_amr_vehicle_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingevent',
            name='vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
